### ISSUE TITLE
Any plans in using the AdonisJS Route lookup?

### ISSUE THREAD

**Issue by thetutlage** [eidellev/adonis-stardust#1]
I see the current logic for making routes in the client side code is quite simple and may fail in certain scenarios like the wildcard route `/uploads/*`.

Also, some of the lookup options from the backend router are missing like. Lookup routes for a domain, or lookup by controller name.

If you want, I can create a PR that replicates the AdonisJS router lookup and URL builder to the client side code. https://github.com/adonisjs/http-server/blob/develop/src/Router/LookupStore.ts

**Comment by eidellev** [comment]
Hey @thetutlage 
Thank you for your feedback 
Agreed, this is a bit of a naive implementation.
I would really appreciate it if you opened a PR like you suggested 🙏

**Comment by thetutlage** [comment]
Closed by https://github.com/eidellev/adonis-stardust/pull/2
