### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by sooluh** [eidellev/adonis-stardust#11]
I used this addon, and it worked at least in development mode. then I changed to production mode, there I activated the Content Security Policy, and this made stardust not work. And after I realized, it turns out that the script tag given by stardust to the view doesn't contain the nonce attribute, so maybe, can you add the nonce attribute in the script tag? Thank you :)

I still can't help (pull request), because I'm new to adonisjs, and I haven't explored until package creation.

**Comment by eidellev** [comment]
@sooluh thank you for reporting this issue, it's greatly appreciated. I will make a fix in the near future.

**Comment by eidellev** [comment]
Starting in `v2.3.0`, the nonce attribute will be automatically added when you enable CSP.

**Comment by sooluh** [comment]
Thanks for your hard work!
I'll use this right now :grin:
