### ISSUE TITLE
Router helper tips

### ISSUE THREAD

**Issue by irfancoder** [eidellev/adonis-stardust#17]
Not a bug. Just wanted to share a neat trick when working with this library, that I think would be helpful to include in the README.

Traditionally in Adonis, we have access to the context instance `eg. params` inside view (.edge) that we can use to help build our dynamic routes. But with inertia, we lose access to the context instance entirely. 

We can overcome this limitation by passing the context instance as a **shared data prop**! 

### Setup
```js
// start/inertia.ts
import Inertia from "@ioc:EidelLev/Inertia";

Inertia.share({
    params: ({ params }) => params
}).version(() => Inertia.manifestFile("public/assets/manifest.json"));
```

### Usage
```js
import { usePage } from "@inertiajs/inertia-react";

const { params } = usePage().props;
stardust.route('users.show', { id: params.id });
```

That's all. I'd be happy to submit a PR if needed

**Comment by eidellev** [comment]
@irfancoder Thanks for the awesome suggestion. I will definitely add this to the readme in the next release.

**Comment by eidellev** [comment]
added in v7.2.0

**Comment by irfancoder** [comment]
Nice! Glad I can help :smile:
