### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by arthur-er** [eidellev/adonis-stardust#7]
### Description

As the library uses ```window``` in some places, we cant render apps on the server.

### Solution

Provide the routes from a config param so we can use stardust in ssr apps

**Comment by eidellev** [comment]
Thanks for reporting this issue. I'm having a hard time visualizing your solution.
Can you provide some (pseudo)code samples of this would work on the server and in the client?

**Comment by arthur-er** [comment]
> Thanks for reporting this issue. I'm having a hard time visualizing your solution. Can you provide some (pseudo)code samples of this would work on the server and in the client?

We can use ziggy implementation as a example (https://github.com/tighten/ziggy/issues/431) and (https://github.com/tighten/ziggy/pull/432)

In inertia contexts we can use the share mecanism to share the routes, in other contexts i think we must rely on the view data

**Comment by arthur-er** [comment]
Looking at the current implementation, i think we can just accept a optional namedRoutes param on initRoutes and it will work for everything except stardust.current()

If the param is not provided, it is retrieved from window

**Comment by eidellev** [comment]
how about if I use `globalThis` instead of window? this way you will have the routes available on the server as well as the client. I think it makes sense in SEO terms as well since you won't have blank links on the initial render

**Comment by eidellev** [comment]
Implemented in v2.2.0
https://github.com/eidellev/adonis-stardust/releases/tag/v2.2.0

@arthur-er I'd appreaciate your help with testing. Let me know there are any issues.
