### ISSUE TITLE
How to add this to inertia vue 3

### ISSUE THREAD

**Issue by eokwukwe** [eidellev/adonis-stardust#9]
Hello @eidellev. Thank you for this package. I am trying to learn `adonis.js` with `inertia.js` for the first time. I am coming from Laravel.

Please, how do I add the package to my inertia frontend? I am using `inertia vue 3`

**Comment by arthur-er** [comment]
Just initialize it in the inertia setup function, by calling the initRoutes function. After that stardust will be available in the vue app

**Comment by eidellev** [comment]
@arthur-er thanks!
@eokwukwe I'm closing this for now. Feel free to open another issue if you run into problems.
